version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: node:10.10.1
      - image: cimg/postgres:14.2.0
        environment:
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
      - image: redis:latest      # context / project UI env-var reference
    working_directory: ~/realServer2
    
    steps:
      - checkout
      - browser-tools/install-browser-tools

      - restore_cache:
         keys:
           - v1-dependencies-{{ checksum "package.json"}} 
           - v1-dependencies-
      - run: npm install
      - save_cache: 
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package.json"}}

         
      - run: npm run coverage

      - run:
          name: "Run mocha and Collect Coverage Reports"
          command: npm run coverage --collectCoverage=true
      - store_artifacts:
          path: coverage
