version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: node:10.10.1
      - image: cimg/postgres:14.2.0
      - image: cimg/node:17.2-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run: npm run test
      - run:
          name: "Run mocha and Collect Coverage Reports"
          command: npm run coverage --collectCoverage=true
      - store_artifacts:
          path: coverage
